# -*- mode: python ; coding: utf-8 -*-
"""
Ninja EXE Build Spec - Standalone GUI Application
"""

block_cipher = None

a = Analysis(
    ['app/ninja_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include web files
        ('app/web', 'web'),
    ],
    hiddenimports=[
        # Telethon
        'telethon',
        'telethon.sync',
        'telethon.sessions',
        'telethon.sessions.sqlite',
        'telethon.tl',
        'telethon.tl.types',
        'telethon.tl.functions',
        'telethon.tl.functions.messages',
        'telethon.tl.functions.users',
        'telethon.tl.functions.contacts',
        'telethon.crypto',
        'telethon.crypto.aes',
        'telethon.crypto.auth_key',
        'telethon.crypto.factorization',
        'telethon.network',
        'telethon.network.connection',
        'telethon.network.connection.tcpfull',
        'telethon.network.authenticator',
        'telethon.extensions',
        'telethon.extensions.markdown',
        'telethon.extensions.html',
        
        # CustomTkinter
        'customtkinter',
        'customtkinter.windows',
        'customtkinter.windows.widgets',
        'customtkinter.windows.widgets.core_widget_classes',
        'customtkinter.windows.widgets.core_rendering',
        'customtkinter.windows.ctk_input_dialog',
        'customtkinter.windows.ctk_toplevel',

        # PIL
        'PIL',
        'PIL.Image',
        'PIL._imaging',
        'PIL._imagingft',
        'PIL._imagingtk',

        # HTTP
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'httpx._content',
        'httpx._auth',
        'httpx._models',
        'h11',
        'h2',
        'h2.connection',
        'h2.events',
        'h2.config',
        'h2.stream',
        'hyperframe',

        # Cryptography
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.default',
        'cryptography.hazmat.backends.openssl',

        # Standard library
        'json',
        'sqlite3',
        'socket',
        'ssl',
        'hashlib',
        'hmac',
        'secrets',
        'base64',
        'binascii',
        'struct',
        'tempfile',
        'shutil',
        'pathlib',
        'datetime',
        'typing',
        'dataclasses',
        'contextlib',
        're',
        'os',
        'sys',
        'time',
        'threading',
        'subprocess',
        'signal',
        'io',
        'logging',
        'queue',
        'ctypes',
        'asyncio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude unused modules
        'tkinter.test',
        'unittest',
        'test',
        'tests',
        'pytest',
        'IPython',
        'jupyter',
        'notebook',
        'numpy',
        'pandas',
        'scipy',
        'matplotlib',
        'cv2',
        'torch',
        'tensorflow',
        'fastapi',
        'uvicorn',
        'starlette',
        'pydantic',
        'setuptools',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Ninja',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
