# -*- mode: python ; coding: utf-8 -*-
"""
Ninja EXE Build Spec
Включает все зависимости для standalone EXE
"""

block_cipher = None

a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include web files
        ('app/web', 'web'),
        # Include ai-proxy if exists
        ('ai-proxy', 'ai-proxy'),
    ],
    hiddenimports=[
        # Telethon
        'telethon',
        'telethon.sync',
        'telethon.sessions',
        'telethon.sessions.sqlite',
        'telethon.tl',
        'telethon.tl.types',
        'telethon.tl.functions',
        'telethon.tl.functions.messages',
        'telethon.tl.functions.users',
        'telethon.tl.functions.contacts',
        'telethon.crypto',
        'telethon.crypto.aes',
        'telethon.crypto.auth_key',
        'telethon.crypto.factorization',
        'telethon.network',
        'telethon.network.connection',
        'telethon.network.connection.tcpfull',
        'telethon.network.authenticator',
        'telethon.extensions',
        'telethon.extensions.markdown',
        'telethon.extensions.html',
        
        # CustomTkinter
        'customtkinter',
        'customtkinter.windows',
        'customtkinter.windows.widgets',
        'customtkinter.windows.widgets.core_widget_classes',
        'customtkinter.windows.widgets.core_rendering',
        'customtkinter.windows.ctk_input_dialog',
        'customtkinter.windows.ctk_toplevel',

        # PIL
        'PIL',
        'PIL.Image',
        'PIL._imaging',
        'PIL._imagingft',
        'PIL._imagingtk',

        # HTTP
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'httpx._content',
        'httpx._auth',
        'httpx._models',
        'h11',
        'h2',
        'h2.connection',
        'h2.events',
        'h2.config',
        'h2.stream',
        'hyperframe',
        'hyperhttp',

        # Cryptography
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.default',
        'cryptography.hazmat.backends.openssl',

        # FastAPI & Uvicorn
        'fastapi',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.responses',
        'fastapi.staticfiles',
        'pydantic',
        'pydantic.fields',
        'pydantic_settings',
        'uvicorn',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.websockets',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.responses',
        'starlette.staticfiles',
        'starlette.templating',
        'anyio',
        'anyio._core',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',

        # Async
        'asyncio',
        'asyncio.subprocess',
        'asyncio.threads',
        'concurrent',
        'concurrent.futures',

        # Standard
        'json',
        'sqlite3',
        'socket',
        'ssl',
        'hashlib',
        'hmac',
        'secrets',
        'base64',
        'binascii',
        'struct',
        'tempfile',
        'shutil',
        'pathlib',
        'datetime',
        'typing',
        'dataclasses',
        'contextlib',
        're',
        'os',
        'sys',
        'time',
        'threading',
        'subprocess',
        'signal',
        'io',
        'logging',
        'logging.handlers',
        'urllib',
        'urllib.parse',
        'urllib.request',
        'uuid',
        'random',
        'math',
        'functools',
        'itertools',
        'collections',
        'enum',
        'types',
        'copy',
        'warnings',
        'traceback',
        'weakref',
        'gc',
        'codecs',
        'locale',
        'gettext',
        'numbers',
        'decimal',
        'fractions',
        'statistics',
        'calendar',
        'argparse',
        'configparser',
        'queue',
        'mmap',
        'ctypes',
        'ctypes.wintypes',
        'winreg',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude unused modules to reduce size
        'tkinter.test',
        'unittest',
        'test',
        'tests',
        'testing',
        'pytest',
        'IPython',
        'jupyter',
        'notebook',
        'sphinx',
        'docutils',
        'email',
        'html',
        'xml',
        'xmlrpc',
        'multiprocessing',
        'concurrent.futures.process',
        'curses',
        'pdb',
        'profile',
        'pstats',
        'doctest',
        'distutils',
        'setuptools',
        'pip',
        'pkg_resources',
        'numpy',
        'pandas',
        'scipy',
        'matplotlib',
        'cv2',
        'torch',
        'tensorflow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Ninja',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Add icon path if needed
)
